spring.application.name=NexChat

# PostgreSQL DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/nexchat_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

# Asgardeo OIDC/OAuth2 Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://api.asgardeo.io/t/praneesh/oauth2/token
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://api.asgardeo.io/t/praneesh/oauth2/jwks
spring.security.oauth2.client.registration.asgardeo.client-id=2kNU1dmiB_kgdZGENh6EQ02gTwga
spring.security.oauth2.client.registration.asgardeo.client-secret=
spring.security.oauth2.client.registration.asgardeo.redirect-uri=http://localhost:5173/
spring.security.oauth2.client.registration.asgardeo.scope=openid,profile
spring.security.oauth2.client.provider.asgardeo.issuer-uri=https://api.asgardeo.io/t/praneesh/oauth2/token
