spring.application.name=NexChat

# PostgreSQL DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/nexchat_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

# Asgardeo OIDC/OAuth2 Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://api.asgardeo.io/t/praneesh/oauth2/token
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://api.asgardeo.io/t/praneesh/oauth2/jwks
spring.security.oauth2.client.registration.asgardeo.client-id=6opH_yoY3peBpNSraDhvzLff7ika
spring.security.oauth2.client.registration.asgardeo.client-secret=qo6Fx6xPoR_NHQguOFqPh1Iir0Fnx1VXmeTLYqngtCQa
spring.security.oauth2.client.registration.asgardeo.redirect-uri=http://localhost:5173/
spring.security.oauth2.client.registration.asgardeo.scope=openid,profile
spring.security.oauth2.client.provider.asgardeo.issuer-uri=https://api.asgardeo.io/t/praneesh/oauth2/token

# Asgardeo User Management API
asgardeo.api.base-url=https://console.asgardeo.io/t/praneesh/
asgardeo.api.token=c33e80e0-987d-3a79-bfa1-cf620193d161
